### ISSUE TITLE
Jenkins alternatives

### ISSUE THREAD

**Issue by targos** [nodejs/Future-CI#6]
Let's put here what we can find that already exists out there.

**Comment by jbergstroem** [comment]
Buildbot, esp. the upcoming nine series: http://buildbot.readthedocs.org

**Comment by targos** [comment]
FWIW Buildbot is the one used by Google for Chromium/V8

**Comment by orangemocha** [comment]
https://github.com/Strider-CD/strider is written in Node.js already

**Comment by rosskukulinski** [comment]
I promise I'm not trolling, but Jenkins: https://jenkins.io/2.0/

**Comment by yorkie** [comment]
Wow, Jenkins v2 looks good to me 👍

**Comment by Trott** [comment]
I know this repo is pretty dormant, but @kahwee has asked me about it a few times, so @-mentioning them to bring them into the conversation...

**Comment by DavidTPate** [comment]
Yeah Jenkins v2 is looking pretty promising.

**Comment by jbergstroem** [comment]
Since I'm not very into Jenkins 2 (as in, what's new etc) -- what makes it better than jenkins 1.x? The pipeline plugin as I understand it has been around since 1.x.

**Comment by gtirloni** [comment]
I could be very wrong, but I guess it's mostly the Pipeline plugin and faster releases. The [Blue Ocean](https://jenkins.io/blog/2016/05/26/introducing-blue-ocean/) interface looks promising but it's a long road.

We've been using 2.x since the release day (without pipelines) and, although it looked like a new promising era had started, it continues to be exhausting. Every single day something new is broken in a different way. It's making me hate CI.

**Comment by DavidTPate** [comment]
@jbergstroem It's definitely the promise of Jenkins v2 that is the promising part. The fact that they are investing time into building the core is what I am excited about. Pipelines are where I am anticipating some additional growth as the feature are fleshed out more.

There's also a ton of refactoring/restructuring that has gone into Jenkins v2 compared to v1. I think all of this could serve as a good point to allow us to contribute to Jenkins v2 to make it better for the end user. Making our own system is quite an undertaking, but there's definitely parts available such as Travis so that we could do that.

**Comment by kahwee** [comment]
@DavidTPate Does Travis allow us to add in our devices in their test matrix?

**Comment by DavidTPate** [comment]
@kahwee My bad, I typed `Travis v2` but I meant `Jenkins v2`, thanks for catching that I've edited my comment to fix that.
